services:
  - type: web
    name: project-test
    env: python
    buildCommand: |
      apt-get update && apt-get install -y gnuplot
      pip install -r requirements.txt
    startCommand: python main.py