services:
  - type: web
    name: project-test # Your Render service name (from dashboard URL)
    env: python
    buildCommand: |
      apt-get update -y
      apt-get install -y gnuplot
      pip install -r requirments.txt
    startCommand: python main.py